export type Degree={id:string;name:string;field:string;tagline:string;description:string;subjects:string[];interests:string[];skills:string[];roles:string[];trial:string;color:string};
export const degrees:Degree[]=[
{id:'civil',name:'Civil engineering',field:'Engineering',tagline:'Shape the places we call home.',description:'Explore how structures, transport and water systems are planned and built. Combine mathematical thinking with practical design and site work.',subjects:['Mathematics','Physics'],interests:['Building','Problem solving','Environment'],skills:['Drawing interpretation','Spreadsheets','Quantity estimation','Technical writing'],roles:['Site engineer','Quantity surveyor','Transport planner'],trial:'Sketch a familiar room, label its dimensions, then estimate the floor area. Write down what you would need to verify on site.',color:'blue'},
{id:'economics',name:'Economics',field:'Social sciences',tagline:'Make sense of the choices around us.',description:'Study how people, businesses and governments make decisions. Use models, evidence and careful argument to understand real problems.',subjects:['Mathematics','Economics'],interests:['Research','Numbers','Society'],skills:['Statistics','Spreadsheets','Research','Data visualisation'],roles:['Research assistant','Economic analyst','Policy researcher'],trial:'Choose a local price that has changed. Write three possible explanations and identify data that could distinguish between them.',color:'green'},
{id:'design',name:'Visual communication',field:'Arts & design',tagline:'Give ideas a form people understand.',description:'Work with typography, imagery and visual systems. Develop ideas through research, making, critique and iteration.',subjects:['Art','English'],interests:['Creativity','Storytelling','Design'],skills:['Typography','Visual design','Research','Communication'],roles:['Visual designer','Editorial designer','Brand designer'],trial:'Redesign a confusing notice using just two type sizes and one colour. Ask someone what they notice first.',color:'peach'},
{id:'business',name:'Business administration',field:'Business',tagline:'Turn ideas into organised action.',description:'Explore marketing, operations, finance and management. Learn to understand customers, work with teams and make evidence-informed decisions.',subjects:['Business','Mathematics','English'],interests:['Leadership','Numbers','People'],skills:['Spreadsheets','Communication','Research','Project planning'],roles:['Operations associate','Marketing associate','Business analyst'],trial:'Interview a small business owner about one daily bottleneck. Propose a simple way to measure and improve it.',color:'blue'},
{id:'psychology',name:'Psychology',field:'Social sciences',tagline:'Understand people with curiosity and care.',description:'Study behaviour, cognition and research methods. Professional clinical practice requires further qualifications and supervised training.',subjects:['Biology','English'],interests:['People','Research','Society'],skills:['Research','Statistics','Communication','Technical writing'],roles:['Research assistant','People operations associate','Behavioural research assistant'],trial:'Compare two published explanations of a learning habit. Identify the evidence each uses; do not diagnose yourself or anyone else.',color:'green'},
{id:'computing',name:'Computer science',field:'Technology',tagline:'Build tools that solve useful problems.',description:'Explore algorithms, software and systems. Combine problem solving with testing, collaboration and clear communication.',subjects:['Mathematics','Computer Science'],interests:['Problem solving','Building','Technology'],skills:['Python','SQL','Git','Communication'],roles:['Software developer','Data analyst','QA engineer'],trial:'Write out the steps for a tool that organises study tasks. Build the smallest version and test three edge cases.',color:'blue'},
{id:'mechanical',name:'Mechanical engineering',field:'Engineering',tagline:'Understand how things move and work.',description:'Investigate mechanics, materials, energy and manufacturing. Move between analytical models, design decisions and physical constraints.',subjects:['Mathematics','Physics'],interests:['Building','Problem solving','Design'],skills:['Drawing interpretation','Spreadsheets','Technical writing','Project planning'],roles:['Design engineer','Manufacturing engineer','Maintenance engineer'],trial:'Choose a everyday mechanism. Draw its moving parts and explain one trade-off in its design.',color:'peach'},
{id:'english',name:'English & humanities',field:'Humanities',tagline:'Read closely. Think deeply. Tell better stories.',description:'Explore language, literature and culture. Develop analysis, writing and research skills that transfer into many kinds of work.',subjects:['English','History'],interests:['Storytelling','Society','Creativity'],skills:['Technical writing','Research','Communication','Editing'],roles:['Editorial assistant','Communications associate','Content researcher'],trial:'Compare how two writers describe the same event. Explain how language changes the reader’s interpretation.',color:'green'},
{id:'electrical',name:'Electrical engineering',field:'Engineering',tagline:'Connect energy, signals and systems.',description:'Explore circuits, power, electronics and control. Develop analytical and design skills with careful practical verification.',subjects:['Mathematics','Physics'],interests:['Technology','Problem solving','Building'],skills:['Python','Technical writing','Spreadsheets','Project planning'],roles:['Electrical design engineer','Controls engineer','Power systems engineer'],trial:'Draw a block diagram for a solar-powered light. Identify its inputs, outputs and safety constraints; do not wire mains equipment.',color:'blue'},
{id:'software',name:'Software engineering',field:'Technology',tagline:'Design software people can rely on.',description:'Go beyond writing code: learn requirements, testing, collaboration and the lifecycle of real products.',subjects:['Mathematics','Computer Science'],interests:['Technology','Problem solving','Building'],skills:['Python','Git','SQL','Project planning'],roles:['Software engineer','QA engineer','Product engineer'],trial:'Write a one-page spec for an app you use, then list three tests that would prove it works.',color:'blue'},
{id:'datasci',name:'Data science',field:'Technology',tagline:'Find the story hiding in the numbers.',description:'Combine statistics, programming and communication to turn data into decisions. Ethics and uncertainty matter as much as models.',subjects:['Mathematics','Computer Science'],interests:['Numbers','Research','Technology'],skills:['Statistics','Python','SQL','Data visualisation'],roles:['Data analyst','Research data assistant','Business intelligence associate'],trial:'Download a small public dataset. Summarise it with one chart and one sentence about what you cannot yet conclude.',color:'green'},
{id:'architecture',name:'Architecture',field:'Arts & design',tagline:'Give buildings a purpose and a feeling.',description:'Study space, light, structure and how people live. Studio work sits beside history, drawing and technical constraints.',subjects:['Mathematics','Art','Physics'],interests:['Design','Building','Creativity'],skills:['Drawing interpretation','CAD','Visual design','Technical writing'],roles:['Architectural intern','Urban design assistant','Conservation assistant'],trial:'Photograph a street you know. Sketch how sunlight, shade and walking paths change across the day.',color:'peach'},
{id:'accounting',name:'Accounting & finance',field:'Business',tagline:'Make money’s story readable.',description:'Learn how organisations record, report and decide. Accuracy, ethics and clear explanation sit at the centre of the work.',subjects:['Mathematics','Accounting','Business'],interests:['Numbers','Research','Leadership'],skills:['Accounting','Spreadsheets','Statistics','Technical writing'],roles:['Accounts assistant','Audit intern','Financial analyst intern'],trial:'Track one week of personal spending in a simple ledger. Categorise it and write what the numbers reveal.',color:'blue'},
{id:'law',name:'Law',field:'Humanities',tagline:'Read carefully. Argue fairly.',description:'Explore legal systems, rights and procedure. Professional practice in Pakistan requires further qualification and enrolment rules.',subjects:['English','History'],interests:['Society','Research','Storytelling'],skills:['Legal research','Technical writing','Communication','Research'],roles:['Legal intern','Compliance assistant','Policy researcher'],trial:'Read a short public statute or judgment summary. Write the issue, the rule, and one open question in plain language.',color:'green'},
{id:'media',name:'Media & journalism',field:'Humanities',tagline:'Ask better questions. Tell truer stories.',description:'Practise reporting, editing and multimedia. Verification and ethics come before speed.',subjects:['English','History'],interests:['Storytelling','Society','Creativity'],skills:['Editing','Research','Communication','Public speaking'],roles:['Editorial intern','Social content associate','Research reporter'],trial:'Interview someone about a local issue. Write 200 words with two named sources and one thing you could not verify.',color:'peach'},
{id:'biotech',name:'Biotechnology',field:'Sciences',tagline:'Use living systems with care and method.',description:'Connect biology, chemistry and lab practice. Further study is common before independent laboratory or clinical work.',subjects:['Biology','Chemistry'],interests:['Research','Health','Problem solving'],skills:['Laboratory methods','Research','Technical writing','Statistics'],roles:['Lab assistant','Quality control intern','Research technician'],trial:'Explain how a household fermentation (yoghurt or dough) depends on conditions you can measure. Do not handle unknown cultures.',color:'green'},
{id:'ir',name:'International relations',field:'Social sciences',tagline:'See how countries, people and ideas meet.',description:'Study politics, history and institutions. Strong writing and careful use of sources matter more than slogans.',subjects:['English','History'],interests:['Society','Research','Leadership'],skills:['Research','Technical writing','Communication','Public speaking'],roles:['Research assistant','Diplomatic support intern','NGO programme assistant'],trial:'Compare two newspaper accounts of the same international event. List what each emphasises and what is missing.',color:'blue'},
{id:'education',name:'Education',field:'Social sciences',tagline:'Help someone else learn, on purpose.',description:'Explore how people learn, how lessons are designed, and how classrooms actually work. Licensing rules vary by role and province.',subjects:['English','Psychology'],interests:['Teaching','People','Society'],skills:['Teaching','Communication','Project planning','Research'],roles:['Teaching assistant','Learning support intern','Curriculum assistant'],trial:'Teach a 10-minute skill to a friend. Note what they understood, what confused them, and what you would change.',color:'peach'},
{id:'agriculture',name:'Agriculture',field:'Sciences',tagline:'Work with land, food and climate.',description:'Study crops, soil, water and rural livelihoods. Field observation sits beside science and economics.',subjects:['Biology','Chemistry'],interests:['Environment','Agriculture','Research'],skills:['Research','Spreadsheets','GIS','Technical writing'],roles:['Farm advisory intern','Agri-research assistant','Supply-chain assistant'],trial:'Visit a fruit or vegetable stall. Trace one item back as far as you can and note water, season and transport questions.',color:'green'},
{id:'chemical',name:'Chemical engineering',field:'Engineering',tagline:'Turn raw materials into useful processes.',description:'Learn mass and energy balances, safety and plant thinking. Laboratory and industrial work need supervision and training.',subjects:['Mathematics','Chemistry','Physics'],interests:['Problem solving','Building','Technology'],skills:['Spreadsheets','Laboratory methods','Technical writing','Project planning'],roles:['Process intern','HSE intern','Quality engineer intern'],trial:'Sketch the steps from milk to packaged yoghurt. Label energy, waste and a safety check at each stage.',color:'blue'},
{id:'nursing',name:'Nursing',field:'Health',tagline:'Care with skill, not just kindness.',description:'Combine patient care, observation and teamwork. Professional practice requires accredited training and licensing.',subjects:['Biology','Chemistry','English'],interests:['Health','People','Problem solving'],skills:['Patient care','Clinical observation','Communication','Technical writing'],roles:['Nursing student clinician','Community health intern','Ward assistant (supervised)'],trial:'Write a clear handover note for a fictional patient using only observations, not diagnosis. Do not practise clinical procedures.',color:'peach'},
{id:'pharmacy',name:'Pharmacy',field:'Health',tagline:'Medicines, evidence and careful advice.',description:'Study how medicines are made, checked and explained. Dispensing and clinical roles require professional qualification.',subjects:['Chemistry','Biology'],interests:['Health','Research','Numbers'],skills:['Chemistry lab','Research','Communication','Technical writing'],roles:['Pharmacy intern','Regulatory assistant','Quality control intern'],trial:'Read a public medicine leaflet. Explain dose, storage and one caution in everyday language.',color:'green'},
{id:'medicine',name:'Medicine (MBBS pathway)',field:'Health',tagline:'A long training in service of patients.',description:'Explore whether clinical medicine is the right demanding path. Admission is competitive; practice requires years of supervised training.',subjects:['Biology','Chemistry','Physics'],interests:['Health','People','Research'],skills:['Clinical observation','Research','Communication','Laboratory methods'],roles:['Medical student','Research assistant','Community health volunteer'],trial:'Shadow a public health campaign poster: rewrite it so a family member would know what to do next. This is not clinical training.',color:'blue'},
{id:'environmental',name:'Environmental science',field:'Sciences',tagline:'Measure the living world, then protect it.',description:'Study ecosystems, pollution and climate through fieldwork and data. Policy and science have to talk to each other.',subjects:['Biology','Chemistry','Geography'],interests:['Environment','Research','Society'],skills:['GIS','Statistics','Research','Technical writing'],roles:['Environmental intern','Conservation assistant','ESG research assistant'],trial:'Walk a local drain or park. Note three human impacts and one measurement you could collect safely.',color:'green'},
{id:'physics',name:'Physics',field:'Sciences',tagline:'Explain the rules the universe runs on.',description:'Build models, test them, and learn to live with uncertainty. A physics degree opens research, teaching, data and engineering-adjacent work.',subjects:['Mathematics','Physics'],interests:['Numbers','Problem solving','Research'],skills:['Statistics','Python','Technical writing','Research'],roles:['Research intern','Lab demonstrator','Data analyst'],trial:'Take a falling-object video. Estimate time and distance, then list every assumption you made.',color:'blue'},
{id:'maths',name:'Mathematics',field:'Sciences',tagline:'Find structure, then use it.',description:'Develop proof, modelling and quantitative reasoning. Careers range from teaching and research to finance and data.',subjects:['Mathematics'],interests:['Numbers','Problem solving','Research'],skills:['Statistics','Python','Research','Technical writing'],roles:['Actuarial intern','Teaching assistant','Quantitative analyst intern'],trial:'Explain a familiar number (inflation, cricket strike rate, or a bill) with a formula and a limitation of that formula.',color:'peach'},
{id:'publicadmin',name:'Public administration',field:'Social sciences',tagline:'Make institutions work for people.',description:'Study how government and public services are organised, funded and held to account.',subjects:['English','Economics'],interests:['Society','Leadership','People'],skills:['Research','Project planning','Communication','Technical writing'],roles:['Government intern','Programme assistant','Policy researcher'],trial:'Map one local public service (a NADRA office, school or clinic). Note the steps a citizen actually takes.',color:'green'},
{id:'hospitality',name:'Hospitality & tourism',field:'Business',tagline:'Host people well, at scale.',description:'Learn operations, service and destination management. People skills sit beside spreadsheets and standards.',subjects:['English','Business'],interests:['People','Leadership','Creativity'],skills:['Communication','Project planning','Spreadsheets','Public speaking'],roles:['Front-office intern','Events assistant','Guest experience associate'],trial:'Review a hotel or restaurant visit: three things that worked, one bottleneck, and a measurable fix.',color:'peach'},
{id:'islamic',name:'Islamic studies',field:'Humanities',tagline:'Read tradition with depth and care.',description:'Study texts, history and contemporary questions. Language, source criticism and teaching skills transfer widely.',subjects:['Islamic Studies','Arabic','English'],interests:['Research','Society','Teaching'],skills:['Arabic','Research','Teaching','Technical writing'],roles:['Research assistant','Curriculum assistant','Community education intern'],trial:'Compare two translations of a short passage. Note one word that changes the meaning and why.',color:'blue'},
{id:'dentistry',name:'Dentistry',field:'Health',tagline:'Precision, patience and clinical care.',description:'A clinical professional path with competitive admission and licensed practice after accredited training.',subjects:['Biology','Chemistry','Physics'],interests:['Health','Problem solving','People'],skills:['Clinical observation','Laboratory methods','Communication','Patient care'],roles:['Dental student','Clinic assistant (supervised)','Oral-health outreach intern'],trial:'Design a one-page oral-health guide for a school. Keep claims limited to widely accepted public-health advice.',color:'green'},
{id:'textile',name:'Textile & fashion design',field:'Arts & design',tagline:'Material, pattern and the clothes we live in.',description:'Work with cloth, colour, making and markets. Studio practice meets industry constraints.',subjects:['Art','Chemistry'],interests:['Creativity','Design','Building'],skills:['Visual design','Project planning','Communication','Research'],roles:['Design intern','Merchandising assistant','Textile lab intern'],trial:'Take apart (or carefully inspect) a worn garment. Sketch its construction and one way you would improve it.',color:'peach'}
];
export type Resource={id:string;title:string;provider:string;url:string;skills:string[];format:'Lessons'|'Textbook'|'Video';language:string;access:string;practice:string};
export const resources:Resource[]=[
{id:'excel',title:'Build confidence with spreadsheets',provider:'GCFGlobal',url:'https://edu.gcfglobal.org/en/excel/',skills:['Spreadsheets','Quantity estimation'],format:'Lessons',language:'English',access:'Free learning',practice:'Build a small budget or material-cost worksheet. Include formulas, units and a check of your totals.'},
{id:'stats',title:'Statistics and probability',provider:'Khan Academy',url:'https://www.khanacademy.org/math/statistics-probability',skills:['Statistics','Data visualisation'],format:'Lessons',language:'English',access:'Free learning',practice:'Summarise a small public dataset with a chart, a measure of centre and a note on uncertainty.'},
{id:'economy',title:'The Economy',provider:'CORE Econ',url:'https://www.core-econ.org/',skills:['Research','Statistics'],format:'Textbook',language:'English',access:'Free open-access books',practice:'Choose one economic question and write a short evidence-based explanation using a chart.'},
{id:'design',title:'Graphic design foundations',provider:'GCFGlobal',url:'https://edu.gcfglobal.org/en/beginning-graphic-design/',skills:['Typography','Visual design'],format:'Lessons',language:'English',access:'Free learning',practice:'Create a one-page poster, then explain your hierarchy, spacing and type choices.'},
{id:'writing',title:'Writing and research resources',provider:'Purdue OWL',url:'https://owl.purdue.edu/owl/',skills:['Technical writing','Editing','Research','Communication'],format:'Lessons',language:'English',access:'Free reference resources',practice:'Write a one-page report for a non-specialist. Cite sources and revise after feedback.'},
{id:'python',title:'Learn scientific computing with Python',provider:'freeCodeCamp',url:'https://www.freecodecamp.org/learn/scientific-computing-with-python/',skills:['Python'],format:'Lessons',language:'English',access:'Free learning',practice:'Build a small script that solves one repetitive task and document three test cases.'},
{id:'sql',title:'Interactive SQL lessons',provider:'SQLBolt',url:'https://sqlbolt.com/',skills:['SQL'],format:'Lessons',language:'English',access:'Free learning',practice:'Write queries that filter, group and join a small dataset. Explain what each result means.'},
{id:'git',title:'Pro Git',provider:'Git',url:'https://git-scm.com/book/en/v2',skills:['Git'],format:'Textbook',language:'English',access:'Free online book',practice:'Create a repository, make a branch and merge a small documented change.'},
{id:'engineering',title:'Civil and environmental engineering',provider:'MIT OpenCourseWare',url:'https://ocw.mit.edu/search/?d=Civil%20and%20Environmental%20Engineering',skills:['Drawing interpretation','Quantity estimation'],format:'Lessons',language:'English',access:'Free course materials',practice:'Choose introductory materials, annotate a simple plan and explain assumptions. Ask a qualified mentor to check technical work.'},
{id:'planning',title:'Project management learning',provider:'OpenLearn',url:'https://www.open.edu/openlearn/money-business/project-management',skills:['Project planning'],format:'Lessons',language:'English',access:'Free learning',practice:'Plan a small project with scope, milestones, dependencies and a risk register.'},
{id:'stats-video',title:'Probability explained with examples',provider:'Khan Academy · YouTube',url:'https://www.youtube.com/watch?v=yUaI0JriZtY',skills:['Statistics'],format:'Video',language:'English',access:'Free video',practice:'Solve two probability examples and explain your reasoning in plain language.'}
];
export type University={id:string;name:string;short:string;city:string;programme:string;degreeId:string;url:string;fee:number|null;mandatory:number|null;feeUrl?:string;feeYear?:string;rule:'nust-social'|'nust-engineering'|'unknown';checked:string};
const nustFee='https://nust.edu.pk/admissions/fee-structure/undergraduate-financial-matters/';
export const universities:University[]=[
{id:'nust-civil',name:'National University of Sciences & Technology',short:'NUST',city:'Islamabad',programme:'Civil engineering · SCEE',degreeId:'civil',url:'https://nust.edu.pk/admissions/undergraduates/',fee:216750,mandatory:5000,feeUrl:nustFee,feeYear:'2026–27',rule:'nust-engineering',checked:'2026-09-07'},
{id:'nust-econ',name:'National University of Sciences & Technology',short:'NUST',city:'Islamabad',programme:'BS Economics · S3H',degreeId:'economics',url:'https://nust.edu.pk/admissions/undergraduates/',fee:302950,mandatory:5000,feeUrl:nustFee,feeYear:'2026–27',rule:'nust-social',checked:'2026-09-07'},
{id:'uet',name:'University of Engineering and Technology',short:'UET',city:'Lahore',programme:'Engineering programmes · explore current offering',degreeId:'civil',url:'https://apply.uet.edu.pk/downloads',fee:null,mandatory:null,rule:'unknown',checked:'2026-09-07'},
{id:'iba',name:'Institute of Business Administration',short:'IBA',city:'Karachi',programme:'Undergraduate business & economics · explore offering',degreeId:'business',url:'https://admissions.iba.edu.pk/',fee:null,mandatory:null,rule:'unknown',checked:'2026-09-07'},
{id:'nca',name:'National College of Arts',short:'NCA',city:'Lahore',programme:'Arts & design · confirm current programmes',degreeId:'design',url:'https://nca.edu.pk/',fee:null,mandatory:null,rule:'unknown',checked:'2026-09-07'}
];
export const sourceLinks={ibcc:'https://ibcc.edu.pk/faqs/equivalence-faqs/',hec:'https://www.hec.gov.pk/english/services/universities/pqr/Pages/default.aspx',nustEligibility:'https://nust.edu.pk/admissions/undergraduates/eligibility-criteria-for-ug-programmes/',nustMerit:'https://nust.edu.pk/admissions/undergraduates/merit-criteria-for-admission-on-net-basis/'};
export const roles=[
{id:'site',title:'Civil engineering intern',degreeId:'civil',city:'Lahore',description:'Example role brief, not a live vacancy. Support a site team with drawing interpretation, spreadsheets and quantity estimation. Prepare clear technical writing for site reports. Currently enrolled in a relevant engineering degree. Site safety induction and supervision required.'},
{id:'research',title:'Economic research assistant',degreeId:'economics',city:'Islamabad',description:'Example role brief, not a live vacancy. Support research using statistics, spreadsheets and data visualisation. Summarise findings through technical writing. Relevant undergraduate degree or current enrolment required. Familiarity with SQL is preferred.'},
{id:'visual',title:'Junior visual designer',degreeId:'design',city:'Karachi',description:'Example role brief, not a live vacancy. Use typography and visual design to produce layouts. Show communication skills and research behind your decisions. A portfolio is required; a degree is preferred.'},
{id:'operations',title:'Operations associate',degreeId:'business',city:'Remote',description:'Example role brief, not a live vacancy. Support operations with spreadsheets, project planning and communication. Use research to document processes. Relevant degree preferred.'},
{id:'developer',title:'Junior software developer',degreeId:'computing',city:'Remote',description:'Example role brief, not a live vacancy. Build small services using Python, SQL and Git. Clear communication and documented projects are required. Relevant degree preferred.'},
{id:'editor',title:'Editorial assistant',degreeId:'english',city:'Lahore',description:'Example role brief, not a live vacancy. Support research, editing and technical writing. Strong communication and a writing portfolio required.'}
];
export const qualifications=['Matric','FSc','FA','ICS','ICom','O-levels','A-levels','Other equivalent'] as const;
export const interestOptions=['Building','Problem solving','Environment','Research','Numbers','Society','Creativity','Storytelling','Design','Leadership','People','Technology'];
export const skillNames=Array.from(new Set(degrees.flatMap(d=>d.skills))).sort();
