import {degrees,resources,skillNames,type University} from './catalogue';
export type Profile={name:string;stage:string;qualification:string;subjects:string[];interests:string[];skills:string[];city:string;budget:number|null;hours:number;ssc:number|null;hssc:number|null;equivalence:boolean;net:number|null;goal:string;relocate:boolean};
export const emptyProfile:Profile={name:'',stage:'Choosing a degree',qualification:'FSc',subjects:[],interests:[],skills:[],city:'',budget:null,hours:5,ssc:null,hssc:null,equivalence:false,net:null,goal:'',relocate:false};
export function recommend(p:Profile){return degrees.map(d=>{const interests=d.interests.filter(i=>p.interests.includes(i));const subjects=d.subjects.filter(i=>p.subjects.includes(i));return {...d,reasons:[...interests.map(i=>`You enjoy ${i.toLowerCase()}`),...subjects.map(i=>`Connects with ${i}`)],score:interests.length*2+subjects.length}}).sort((a,b)=>b.score-a.score)}
export function assessUniversity(u:University,p:Profile){
 const cost=u.fee!==null&&u.mandatory!==null?u.fee+u.mandatory:null;
 const budget=cost===null?'Costs need checking':p.budget===null?'Add your budget':cost<=p.budget?'Within semester budget':'Above semester budget';
 const base={budget,cost,aggregate:null as number|null};
 if(p.qualification==='Matric'||p.qualification==='O-levels')return {...base,status:'Next qualification needed',detail:'Explore higher-secondary/A-level pathways before assessing undergraduate admission.'};
 if(u.rule==='unknown')return {...base,status:'Check current admissions',detail:'Current programme-specific rules are not verified in this catalogue. Use the official admissions page.'};
 if(['A-levels','Other equivalent'].includes(p.qualification)&&!p.equivalence)return {...base,status:'Equivalence needed',detail:'Add your official IBCC SSC and HSSC equivalence percentages. Raw grades are not converted here.'};
 if(p.ssc===null||p.hssc===null)return {...base,status:'Add academic results',detail:'Both SSC and HSSC/equivalent percentages are needed for the published minimum check.'};
 if(p.ssc<60||p.hssc<60)return {...base,status:'Below published minimum',detail:'NUST lists a minimum of 60% in each of SSC and HSSC/equivalent. Check the official page for your route.'};
 if(u.rule==='nust-engineering')return {...base,status:'Subject route needs review',detail:'Check science group, subject combination and any remedial requirements against the official engineering criteria. Marks alone do not establish eligibility.'};
 if(p.net===null)return {...base,status:'Academic minimum met',detail:'Add a NET percentage to estimate the standard completed-qualification aggregate. Test route and other admission requirements still apply.'};
 return {...base,status:'Academic minimum met',aggregate:Math.round((p.ssc*.1+p.hssc*.15+p.net*.75)*100)/100,detail:'Standard NET route, completed SSC/HSSC or equivalence: 10% SSC + 15% HSSC + 75% NET. Not an admission offer or closing-merit prediction.'};
}
const aliases:Record<string,string[]>={'Spreadsheets':['excel','spreadsheets','spreadsheet'],'Drawing interpretation':['drawing interpretation','technical drawings','engineering drawings'],'Quantity estimation':['quantity estimation','quantity surveying','bill of quantities','boq'],'Technical writing':['technical writing','report writing','site reports'],'Data visualisation':['data visualisation','data visualization'],'Communication':['communication','presentation skills'],'Research':['research'],'Visual design':['visual design','graphic design'],'Typography':['typography'],'Statistics':['statistics','statistical analysis'],'Project planning':['project planning','project management'],'Editing':['editing','proofreading'],'Python':['python'],'SQL':['sql'],'Git':['git','version control']};
function escape(s:string){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
export type Gap={skill:string;status:'Self-reported'|'Not yet demonstrated';evidence:string;optional:boolean};
export function analyseJob(text:string,skills:string[]):{gaps:Gap[];formal:string[];method:string}{
 const lines=text.split(/(?<=[.!?])\s+|\n|;/).map(s=>s.trim()).filter(Boolean);
 const gaps:Gap[]=[];
 for(const skill of skillNames){for(const sentence of lines){const re=new RegExp(`\\b(?:${(aliases[skill]||[skill]).map(escape).join('|')})\\b`,'i');const match=re.exec(sentence);if(!match)continue;const before=sentence.slice(Math.max(0,match.index-35),match.index);const after=sentence.slice(match.index+match[0].length,match.index+match[0].length+40);if(/(?:no|without|not requiring)\s+(?:prior\s+)?$/i.test(before)||/^\s*(?:experience\s+)?(?:is\s+)?(?:not required|isn't required|unnecessary)/i.test(after))continue;gaps.push({skill,status:skills.some(s=>s.toLowerCase()===skill.toLowerCase())?'Self-reported':'Not yet demonstrated',evidence:sentence.slice(0,400),optional:/preferred|optional|nice.to.have/i.test(sentence)});break}}
 return {gaps,formal:lines.filter(s=>/\b(degree|enrol|enroll|licen[cs]e|portfolio|years? of experience|induction|supervision)\b/i.test(s)).slice(0,8),method:'Keyword-assisted analysis. Review the original wording; nuanced requirements may need correction.'};
}
export type Milestone={id:string;skill:string;title:string;resourceId:string|null;practice:string;hours:number;done:boolean};
export type Plan={id:string;title:string;goal:string;hoursPerWeek:number;milestones:Milestone[];createdAt:string};
export function createPlan(goal:string,skills:string[],hours:number):Plan{const wanted=Array.from(new Set(skills)).filter(s=>skillNames.includes(s)).slice(0,8);return{id:crypto.randomUUID(),title:`Your path to ${goal}`,goal,hoursPerWeek:Math.max(1,Math.min(30,hours)),createdAt:new Date().toISOString(),milestones:wanted.map((skill,i)=>{const r=resources.find(r=>r.skills.includes(skill));return{id:`step-${i}`,skill,title:`Build evidence of ${skill.toLowerCase()}`,resourceId:r?.id||null,practice:r?.practice||`Complete a small practical task demonstrating ${skill.toLowerCase()} and request feedback.`,hours:4,done:false}})}}
export function exportPlan(p:Plan){return `# ${p.title}\n\n${p.hoursPerWeek} hours per week. Estimated practice time; adjust to your starting level.\n\n`+p.milestones.map((m,i)=>{const r=resources.find(r=>r.id===m.resourceId);return `## ${i+1}. ${m.title}\n\n- Status: ${m.done?'Completed':'To do'}\n- Estimated time: ${m.hours} hours\n- Resource: ${r?`${r.title} — ${r.url}`:'Choose a suitable resource'}\n- Practice: ${m.practice}\n`}).join('\n')+'\nCompleting a plan does not guarantee job eligibility or demonstrate independently assessed competence.\n'}
